name: plasmabio-template-python
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - ipywidgets>=7.6,<8
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
