name: plasmabio-template-python
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - conda-forge
  - bioconda
dependencies:
  # Jupyter dependencies
  - jupyterhub>=4.1.6,<5
  - jupyterlab>=4.4,<5
  - notebook>=7.4,<8
  - jupyter-resource-usage>=1,<2
  - jupyterlab-topbar-text >=1.1.0,<2
  - nodejs>=20
  # Python environment
  - python>=3.10,<3.13
  - pip
  - ipywidgets>=8,<9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - biopython
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  - jupyterlab-variableinspector
  - pip:
    # Print module version
    - watermark
