name: plasmabio-template-python
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=4,<5
  - jupyterlab>=4,<5
  - jupyter-resource-usage>=1,<2
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - nodejs>=20
  # Python environment
  - python>=3.10
  - pip
  - ipywidgets>=8,<9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - biopython
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  - jupyterlab-variableinspector
  - pip:
    # Print module version
    - watermark
